sudo: 'required'

services:
  - 'docker'

language:
  - 'bash'

env:
    global:
        - TARGET=raymondmm/emqtt
        - QEMU_VERSION=v3.0.0
    matrix:
        - BUILD_FROM=amd64/alpine:3.7 QEMU_ARCH=x86_64 OS_ARCH=alpine-amd64
        - BUILD_FROM=arm32v6/alpine:3.7 QEMU_ARCH=arm OS_ARCH=alpine-arm32v6
        - BUILD_FROM=arm64v8/alpine:3.7 QEMU_ARCH=aarch64 OS_ARCH=alpine-arm64v8

before_install:
  - ./.docker/docker.sh prepare

install: true

before_script:
    # Set BUILD_VERSION
    - if [ ! -z "${TRAVIS_TAG}" ]; then export BUILD_VERSION=${TRAVIS_TAG}; else export BUILD_VERSION=v2.3.8; fi

script:
    # Build Docker image
    - ./.docker/docker.sh build

    # Test Docker image
    - ./.docker/docker.sh test

    # Push Docker image (TODO move to function)
    - >
      if [ ! -z "${TRAVIS_TAG}" ]; then
        # Tag Docker image
        ./.docker/docker.sh tag

        # Docker Login
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

        # Push Docker image
        docker push ${TARGET}:${BUILD_VERSION}-${OS_ARCH}

        # Docker Logout
        docker logout
      fi

jobs:
    include:
        - stage: manifest
          if: tag =~ ^v
          script:
              # Create and push Docker manifest lists (TODO move to function)
              # Docker Login
              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

              # Create and Push Docker Manifest Lists to Docker Hub
              - echo "Create manifest list for all docker images."
              - ./.docker/docker.sh manifest-list

              # Docker Logout
              - docker logout

# notify me when things fail
notifications:
    email: true
