sudo: 'required'

services:
  - 'docker'

language:
  - 'bash'

env:
  global:
    - TARGET=raymondmm/emqtt
    - QEMU_VERSION=v2.12.0

before_install:
  - ./.docker/docker.sh prepare

before_script:
    # Set EMQ_VERSION
    - if [ ! -z "$TRAVIS_TAG" ]; then export EMQ_VERSION=$TRAVIS_TAG; else export EMQ_VERSION=v2.3.8; fi

script:
  - ./.docker/docker.sh build
  - ./.docker/docker.sh test

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      # Docker Login
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Tag all images
      ./.docker/docker.sh tag

      # Push all images
      ./.docker/docker.sh push

      # Create and push manifest list
      ./.docker/docker.sh manifest-list

      # Docker Logout
      docker logout
    fi

# notify me when things fail
notifications:
    email: true
